# Import Tensorflow 2.0

In [0]:
a = []
while(1):
    a.append('1')

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'2.1.0'

# Numpy Arrays

In [0]:
#Numpy Arrays use less memory space than Python arrays

In [0]:
#@title Declaring an array and assign it to Numpy
import numpy as np
mylist=[1,2,3]
np.array(mylist)

array([1, 2, 3])

In [0]:
#@title Declare a nested array and assign to numpy
nested_list=[[1,2],[3,4],[5,6]]
print(nested_list)

[[1, 2], [3, 4], [5, 6]]


In [0]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#@title Declare numpy array based on range
np.arange(0,100,6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [0]:
#@title Declare numpy array with 5 zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [0]:
#@title Declare numpy array with  zeroes of dimension 4 rows and 5 cols
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
#@title Declare numpy array with  one of dimension 5 rows and 3 cols

np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
#@title Assign n number of variables between a set of numbers

np.linspace(0,100,3)

array([  0.,  50., 100.])

In [0]:

np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [0]:
#@title Create identity matrix of 5x5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
#@title Create random numpy array with 3 numbers
np.random.rand(3)

array([0.3693604 , 0.61654022, 0.72490446])

In [0]:
np.random.rand(3)

In [0]:
#@title Create random numpy array with 3,5 numbers
np.random.rand(3,5)

array([[0.51285915, 0.35375713, 0.11767564, 0.28152399, 0.14808684],
       [0.26175977, 0.54702073, 0.26567813, 0.66371671, 0.63475123],
       [0.8864836 , 0.10020788, 0.79607899, 0.86461332, 0.07564591]])

In [0]:
#@title Generate a Random integer between 2 and exclusive of 10.1
np.random.randint(2,10.1)

7

In [0]:
#@title Generate a Random integer between 2 and exclusive of 10.1 with dimension of 3x3

np.random.randint(2,10.1,(3,3))

array([[7, 8, 5],
       [3, 5, 2],
       [9, 8, 9]])

In [0]:
#@title Initialise seed to ensure same of random no are generated
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [0]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [0]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [0]:
np.random.seed(42)

In [0]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [0]:
customrange=np.arange(0,40,2)
customrange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [0]:
#@title Find dimension(shape) of numpy array

customrange.shape

(5,)

In [0]:
#@title Change dimension(reshape) of numpy array
twodimcustrange=customrange.reshape(4,5)
twodimcustrange

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [0]:
customrange.reshape(5,4)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [0]:
nrange=np.arange(2,40,2)
nrange

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [0]:
#@title Find max in a numpy array
nrange.max()

38

In [0]:
#@title Find index of max in a numpy array
nrange.argmax()

18

In [0]:
#@title Find min in a numpy array
nrange.min()

2

In [0]:
#@title Find index of min in a numpy array
nrange.argmin()

0

In [0]:
#@title Find data type of a numpy array
nrange.dtype

dtype('int64')

# Numpy Index

In [0]:
import numpy as np
arr=np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [0]:
#@title Access 9th element of a numpy array
newarr
arr[8]

24

In [0]:
#@title Access all elements from 2nd to last of a numpy array
arr[1:]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [0]:
#@title Access all elements from 2nd to 4th of a numpy array
arr[1:5]

array([ 3,  6,  9, 12])

In [0]:
#@title Access all elements from beginning to 4th of a numpy array
arr[:5]

array([ 0,  3,  6,  9, 12])

In [0]:
#@title Access all elements from 1st to 4th of a numpy array
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99])

In [0]:
#@title Numpy example of call by reference where original array is changed 
newarr=np.arange(0,100,5)
newarr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [0]:
newarr_cp1=newarr[4:8]
newarr_cp1

array([20, 25, 30, 35])

In [0]:
newarr_cp1[:]=30
newarr_cp1

array([30, 30, 30, 30])

In [0]:
newarr

array([ 0,  5, 10, 15, 30, 30, 30, 30, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [0]:
#@title Numpy example of call by value where original array is retained 
newarr=np.arange(0,100,5)
newarr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [0]:
newarr_cp2=newarr.copy()[4:8]
newarr_cp2

array([20, 25, 30, 35])

In [0]:
newarr_cp2[:]=30
newarr_cp2

array([30, 30, 30, 30])

In [0]:
newarr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [0]:
#@title Declare 2d array in numpy
array_2d

array([[ 4,  9, 25],
       [ 5,  8, 13],
       [ 5,  7, 12]])

In [0]:
#@title Find shape of 2d Numpy array
array_2d.shape

(3, 3)

In [0]:
#@title Access 2nd Row a Numpy 2d array
array_2d[1]

array([ 5,  8, 13])

In [0]:
#@title Access cell value present at 1st row and 3rd column
array_2d[1][2]

13

In [0]:
array_2d[1,2]

13

In [0]:
#@title Slice 2d Numpy array from 1st row and 1st column
array_2d[1:,1:]

array([[ 8, 13],
       [ 7, 12]])

In [0]:
#@title Slice 2d Numpy array from 2nd row and 2nd column to end
array_2d[1:,1:]

In [0]:
#@title Slice 2d Numpy array from 1st:2nd row and 2nd column to end
array_2d[0:2,1:]

array([[ 9, 25],
       [ 8, 13]])

In [0]:
#@title Perform boolean operation on a numpy array
newarr3=np.arange(0,32)
newarr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [0]:
newarr3[(newarr3%4==0)]

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [0]:
#@title Perform mathematical operation on a numpy array
matharray=np.arange(0,40,2)
matharray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [0]:
matharray+2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [0]:
matharray-2

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
       32, 34, 36])

In [0]:
matharray+matharray

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76])

In [0]:
matharray*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76])

In [0]:
matharray*matharray

array([   0,    4,   16,   36,   64,  100,  144,  196,  256,  324,  400,
        484,  576,  676,  784,  900, 1024, 1156, 1296, 1444])

In [0]:
matharray/4

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [0]:
np.sqrt(matharray)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262,
       5.47722558, 5.65685425, 5.83095189, 6.        , 6.164414  ])

In [0]:
np.sin(matharray)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.90557836,  0.76255845,  0.27090579,
       -0.98803162,  0.55142668,  0.52908269, -0.99177885,  0.29636858])

In [0]:
np.log(matharray)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227, 3.09104245, 3.17805383, 3.25809654, 3.33220451,
       3.40119738, 3.4657359 , 3.52636052, 3.58351894, 3.63758616])

In [0]:
matharray.sum()

380

In [0]:
matharray.mean()

19.0

In [0]:
#@title Perform mathematical operation on a numpy matrix or 2d Array

array_2d_math=np.arange(0,25).reshape(5,5)
array_2d_math

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
array_2d_math.sum()

300

In [0]:
array_2d_math.sum(axis=0)

array([50, 55, 60, 65, 70])

In [0]:
array_2d_math.sum(axis=1)


array([ 10,  35,  60,  85, 110])

# Pandas Series

In [0]:
#@title Create Pandas series with list using number index and label index
import numpy as np
import pandas as pd
mylist=[45,58,33]
pd.Series(mylist)

0    45
1    58
2    33
dtype: int64

In [0]:
labels=["Maths","Chemistry","History"]
mylist=[45,58,33]
pd.Series(mylist,labels)

Maths        45
Chemistry    58
History      33
dtype: int64

In [0]:
#@title Create Pandas series using numpy array
nparray=np.array([25,36,78])
pd.Series(nparray,labels)

Maths        25
Chemistry    36
History      78
dtype: int64

In [0]:
#@title Create Pandas series using dictionary
dict={"Runs":456,"Wickets":89}
pd.Series(dict)

Runs       456
Wickets     89
dtype: int64

In [0]:
#@title Access Series using Index and Label
label_cntry1=["USA","Canada","Mexico","India"]
sale1=[34,11,45,32]
ser1=pd.Series(sale1,label_cntry1)

In [0]:
ser1[2]

45

In [0]:
ser1["Mexico"]

45

In [0]:
#@title Add 2 series
label_cntry2=["Canada","Pakistan","India","USA"]
sale2=[100,200,300,400]
ser2=pd.Series(sale2,label_cntry2)

In [0]:
ser1+ser2

Canada      111.0
India       332.0
Mexico        NaN
Pakistan      NaN
USA         434.0
dtype: float64

# Pandas Dataframe

In [0]:
#@title Create Dataframe from Random numbers 
randomnum=np.random.randint(-100,100,20)
randomnum

array([-87, -67,  50,  27, -53,   6, -26, -11,  78,  89,  99,  29, -68,
       -29,  92,  77, -54, -17, -96,  34])

In [0]:
randomnum2d=randomnum.reshape(5,4)
randomnum2d

array([[-87, -67,  50,  27],
       [-53,   6, -26, -11],
       [ 78,  89,  99,  29],
       [-68, -29,  92,  77],
       [-54, -17, -96,  34]])

In [0]:
rowindex=["A","B","C","D","E"]
colindex=["W","X","Y","Z"]

In [0]:
sampleDF=pd.DataFrame(randomnum2d,index=rowindex,columns=colindex)
sampleDF

W   X   Y   Z
A -87 -67  50  27
B -53   6 -26 -11
C  78  89  99  29
D -68 -29  92  77
E -54 -17 -96  34

In [0]:
#@title Access Dataframe using ColumnNames

sampleDF['W']

A   -87
B   -53
C    78
D   -68
E   -54
Name: W, dtype: int64

In [0]:
sampleDF[['W','Z']]

W   Z
A -87  27
B -53 -11
C  78  29
D -68  77
E -54  34

In [0]:
type(sampleDF['W'])

pandas.core.series.Series

In [0]:
type(sampleDF[['W','Z']])

pandas.core.frame.DataFrame

In [0]:
#@title Create New column in Dataframe
sampleDF['NEWCOL']


KeyError: ignored

In [0]:
sampleDF['NEWCOL']=sampleDF['W']+sampleDF['Y']
sampleDF

KeyError: ignored

In [0]:
#@title Drop column in Dataframe
sampleDF=sampleDF.drop(['Y'],axis=1)
sampleDF

KeyError: ignored

In [0]:
#@title Drop row in Dataframe
sampleDF.loc['A']

W        -87
X        -67
Z         27
NEWCOL   -37
Name: A, dtype: int64

In [0]:
sampleDF.loc[['A','E']]

W   X   Z  NEWCOL
A -87 -67  27     -37
E -54 -17  34    -150

In [0]:
sampleDF.iloc[1:3]

W   X   Z  NEWCOL
B -53   6 -11     -79
C  78  89  29     177

In [0]:
sampleDF.drop(['A','E'])

W   X   Z  NEWCOL
B -53   6 -11     -79
C  78  89  29     177
D -68 -29  77      24

In [0]:
#@title Selecting a particular row and column in Dataframe
sampleDF.loc[['A','E'],['X','Z']]

X   Z
A -67  27
E -17  34

In [0]:
#@title Assigning a new column as Index column
sampleDF

W   X   Z  NEWCOL
A -87 -67  27     -37
B -53   6 -11     -79
C  78  89  29     177
D -68 -29  77      24
E -54 -17  34    -150

In [0]:
states=["USA","England","Russia","Poland","Ukraine"]
sampleDF['states']=states

In [0]:
sampleDF

W   X   Z  NEWCOL   states
A -87 -67  27     -37      USA
B -53   6 -11     -79  England
C  78  89  29     177   Russia
D -68 -29  77      24   Poland
E -54 -17  34    -150  Ukraine

In [0]:
sampleDF=sampleDF.set_index('states')
sampleDF

W   X   Z  NEWCOL
states                     
USA     -87 -67  27     -37
England -53   6 -11     -79
Russia   78  89  29     177
Poland  -68 -29  77      24
Ukraine -54 -17  34    -150

In [0]:
#@title The describe() method is used for calculating some statistical data like percentile, mean and std of the numerical values of the Series or DataFrame. It analyzes both numeric and object series and also the DataFrame column sets of mixed data types.
sampleDF.describe()

W          X          Z      NEWCOL
count   5.000000   5.000000   5.000000    5.000000
mean  -36.800000  -3.600000  31.200000  -13.000000
std    65.633071  58.118844  31.260198  123.662848
min   -87.000000 -67.000000 -11.000000 -150.000000
25%   -68.000000 -29.000000  27.000000  -79.000000
50%   -54.000000 -17.000000  29.000000  -37.000000
75%   -53.000000   6.000000  34.000000   24.000000
max    78.000000  89.000000  77.000000  177.000000

In [0]:
#@title  The info() function is used to print a concise summary of a DataFrame. This method prints information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage.
sampleDF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, USA to Ukraine
Data columns (total 4 columns):
W         5 non-null int64
X         5 non-null int64
Z         5 non-null int64
NEWCOL    5 non-null int64
dtypes: int64(4)
memory usage: 200.0+ bytes


# Pandas Filtering Or Subsetting a Dataframe

In [0]:
#@title Select subset of A dataframe and return a Dataframe with Boolean values

In [0]:
import numpy as np
import pandas as pd

In [0]:
randomnum=np.random.randint(-100,100,20)
randomnum

array([ 77, -21,  27,  57, -97, -84,  45,  47,  43,  62,  42, -59, -66,
        41,  44,  68,  20,  11,  79,   9])

In [0]:
randomnum2d=randomnum.reshape(5,4)
randomnum2d

array([[ 77, -21,  27,  57],
       [-97, -84,  45,  47],
       [ 43,  62,  42, -59],
       [-66,  41,  44,  68],
       [ 20,  11,  79,   9]])

In [0]:
rowindex=["A","B","C","D","E"]
colindex=["W","X","Y","Z"]
exampleDF=pd.DataFrame(randomnum2d,rowindex,colindex)
exampleDF

W   X   Y   Z
A  77 -21  27  57
B -97 -84  45  47
C  43  62  42 -59
D -66  41  44  68
E  20  11  79   9

In [0]:
exampleDF>0

W      X     Y      Z
A   True  False  True   True
B  False  False  True   True
C   True   True  True  False
D  False   True  True   True
E   True   True  True   True

In [0]:
#@title Select subset of A dataframe and filter the same instead of returning boolean values
exampleDF[exampleDF>0]

W     X   Y     Z
A  77.0   NaN  27  57.0
B   NaN   NaN  45  47.0
C  43.0  62.0  42   NaN
D   NaN  41.0  44  68.0
E  20.0  11.0  79   9.0

In [0]:
exampleDF

W   X   Y   Z
A  77 -21  27  57
B -97 -84  45  47
C  43  62  42 -59
D -66  41  44  68
E  20  11  79   9

In [0]:
#@title  Return a Series from dataframe with Boolean values based on a condition for a column in dataframe
exampleDF['X']>0

A    False
B    False
C     True
D     True
E     True
Name: X, dtype: bool

In [0]:
#@title  Return a dataframe with actual instead of boolean values based on a condition for a column in dataframe
exampleDF[exampleDF['X']>0]

W   X   Y   Z
C  43  62  42 -59
D -66  41  44  68
E  20  11  79   9

In [0]:
#@title  Return a series with actual instead of boolean values based on a condition for a column in dataframe and then projecting a particular column only
exampleDF[exampleDF['X']>0]['Y']

C    42
D    44
E    79
Name: Y, dtype: int64

In [0]:
#@title  Return a series with actual instead of boolean values based on a condition for a column in dataframe and then projecting a particular row using names

exampleDF[exampleDF['X']>0].loc[['C','E']]

W   X   Y   Z
C  43  62  42 -59
E  20  11  79   9

In [0]:
#@title  Return a series with actual instead of boolean values based on a condition for a column in dataframe and then projecting a particular row using index

exampleDF[exampleDF['X']>0].iloc[['0','2']]

W   X   Y   Z
C  43  62  42 -59
E  20  11  79   9

In [0]:
#@title  Multiple Conditions using And/Or operator
exampleDF

W   X   Y   Z
A  77 -21  27  57
B -97 -84  45  47
C  43  62  42 -59
D -66  41  44  68
E  20  11  79   9

In [0]:
exampleDF[exampleDF['X']>0]

W   X   Y   Z
C  43  62  42 -59
D -66  41  44  68
E  20  11  79   9

In [0]:
exampleDF[exampleDF['Z']>0]

W   X   Y   Z
A  77 -21  27  57
B -97 -84  45  47
D -66  41  44  68
E  20  11  79   9

In [0]:
(exampleDF['X']>0) & (exampleDF['Z']>0)

A    False
B    False
C    False
D     True
E     True
dtype: bool

In [0]:
(exampleDF['X']>0) | (exampleDF['Z']>0)

A    True
B    True
C    True
D    True
E    True
dtype: bool

In [0]:
exampleDF[(exampleDF['X']>0) & (exampleDF['Z']>0)]

W   X   Y   Z
D -66  41  44  68
E  20  11  79   9

In [0]:
exampleDF[(exampleDF['X']>0) | (exampleDF['Z']>0)]

W   X   Y   Z
A  77 -21  27  57
B -97 -84  45  47
C  43  62  42 -59
D -66  41  44  68
E  20  11  79   9

# Pandas Missing Data

In [0]:
#@title  Drop rows with one or more null column

missingDFExample=pd.DataFrame({'A':[1,2,np.nan,4],'B':[5,np.nan,np.nan,8],'C':[10,20,30,40]})
missingDFExample

A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [0]:
missingDFExample.dropna()

A    B   C
0  1.0  5.0  10
3  4.0  8.0  40

In [0]:
#@title  Drop column with one or more null row values

missingDFExample.dropna(axis=1)

C
0  10
1  20
2  30
3  40

In [0]:
#@title  Drop column which atleast has 3 non null values using threshold parameter
missingDFExample.dropna(axis=1,thresh=3)

A   C
0  1.0  10
1  2.0  20
2  NaN  30
3  4.0  40

In [0]:
#@title  Replace null values with a specific value
missingDFExample.dtypes

A    float64
B    float64
C      int64
dtype: object

In [0]:
missingDFExample.fillna("missing value")

A              B   C
0              1              5  10
1              2  missing value  20
2  missing value  missing value  30
3              4              8  40

In [0]:
missingDFExample

A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [0]:
#@title  Replace null values for a particular column

missingDFExample['A']=missingDFExample['A'].fillna("missing value A")
missingDFExample

A    B   C
0                1  5.0  10
1                2  NaN  20
2  missing value A  NaN  30
3                4  8.0  40

In [0]:
#@title  Replace null values with mean
missingDFExample['D']=[30,np.nan,50,np.nan]
missingDFExample

A    B   C     D
0                1  5.0  10  30.0
1                2  NaN  20   NaN
2  missing value A  NaN  30  50.0
3                4  8.0  40   NaN

In [0]:
missingDFExample['D'].mean()

40.0

In [0]:
missingDFExample['B'].fillna(missingDFExample['B'].mean())

0    5.0
1    6.5
2    6.5
3    8.0
Name: B, dtype: float64

In [0]:
missingDFExample.fillna(value=missingDFExample.mean())

A    B   C     D
0                1  5.0  10  30.0
1                2  6.5  20  40.0
2  missing value A  6.5  30  50.0
3                4  8.0  40  40.0

# Pandas GroupBy

In [0]:
import numpy as np
import pandas as pd

In [0]:
empsales=pd.DataFrame([["Jassi",450],["Pradeep",100],["Yogesh",300],["Jassi",200],["Pradeep",600],["Yogesh",900]],columns=["Name","Sales"])
empsales

Name  Sales
0    Jassi    450
1  Pradeep    100
2   Yogesh    300
3    Jassi    200
4  Pradeep    600
5   Yogesh    900

In [0]:
empsales.head()

Name  Sales
0    Jassi    450
1  Pradeep    100
2   Yogesh    300
3    Jassi    200
4  Pradeep    600

In [0]:
#@title  Group by then Sum

empsales.groupby(by='Name').sum()

Sales
Name          
Jassi      650
Pradeep    700
Yogesh    1200

In [0]:
#@title  Group by then Mean

empsales.groupby(by='Name').mean()

Sales
Name          
Jassi      325
Pradeep    350
Yogesh     600

In [0]:
#@title  Sort rows by index after grouping
empsales.groupby(by='Name').mean().sort_index()

Sales
Name          
Jassi      325
Pradeep    350
Yogesh     600

In [0]:
empsales.groupby(by='Name').mean().sort_index(ascending=False)

Sales
Name          
Yogesh     600
Pradeep    350
Jassi      325

In [0]:
#@title  Group by Multiple Columns
empyrsales=pd.DataFrame([["Jassi","2010",450],["Pradeep","2012",100],["Yogesh","2010",300],["Jassi","2010",200],["Pradeep","2016",600],["Yogesh","2014",900]],columns=["Name","Year","Sales"])
empyrsales

Name  Year  Sales
0    Jassi  2010    450
1  Pradeep  2012    100
2   Yogesh  2010    300
3    Jassi  2010    200
4  Pradeep  2016    600
5   Yogesh  2014    900

In [0]:
empyrsales.groupby(by=["Name","Year"]).sum()

Sales
Name    Year       
Jassi   2010    650
Pradeep 2012    100
        2016    600
Yogesh  2010    300
        2014    900

In [0]:
#@title  Combine Group by with describe for useful statistics
empyrsales.groupby(by=["Name"]).describe()

Sales                                                      
        count   mean         std    min    25%    50%    75%    max
Name                                                               
Jassi     2.0  325.0  176.776695  200.0  262.5  325.0  387.5  450.0
Pradeep   2.0  350.0  353.553391  100.0  225.0  350.0  475.0  600.0
Yogesh    2.0  600.0  424.264069  300.0  450.0  600.0  750.0  900.0

In [0]:
empyrsales.groupby(by=["Name"]).describe().transpose()

Name              Jassi     Pradeep      Yogesh
Sales count    2.000000    2.000000    2.000000
      mean   325.000000  350.000000  600.000000
      std    176.776695  353.553391  424.264069
      min    200.000000  100.000000  300.000000
      25%    262.500000  225.000000  450.000000
      50%    325.000000  350.000000  600.000000
      75%    387.500000  475.000000  750.000000
      max    450.000000  600.000000  900.000000

# Pandas Miscellaneous

In [0]:
#@title Unique values for a column in Dataframe
empyrsales['Name']

0      Jassi
1    Pradeep
2     Yogesh
3      Jassi
4    Pradeep
5     Yogesh
Name: Name, dtype: object

In [0]:
empyrsales['Name'].unique()

array(['Jassi', 'Pradeep', 'Yogesh'], dtype=object)

In [0]:
#@title No. of Unique values for a column in Dataframe
empyrsales['Name'].nunique()

3

In [0]:
#@title No. of rows for each unique value for a column
empyrsales['Name'].value_counts()

Pradeep    2
Yogesh     2
Jassi      2
Name: Name, dtype: int64

In [0]:
#@title Derive columns using a function
def startLetter(name):
  return name[0]

In [0]:
startLetter("Mahesh")

'M'

In [0]:
empyrsales['NameStartLetter']=empyrsales['Name'].apply(startLetter)
empyrsales

Name  Year  Sales NameStartLetter
0    Jassi  2010    450               J
1  Pradeep  2012    100               P
2   Yogesh  2010    300               Y
3    Jassi  2010    200               J
4  Pradeep  2016    600               P
5   Yogesh  2014    900               Y

In [0]:
#@title Map to a dictionary value
nameval={"P":1,"Y":2,"J":3}
empyrsales['NameStartLetter']=empyrsales['NameStartLetter'].map(nameval)

In [0]:
empyrsales

Name  Year  Sales  NameStartLetter
0    Jassi  2010    450                3
1  Pradeep  2012    100                1
2   Yogesh  2010    300                2
3    Jassi  2010    200                3
4  Pradeep  2016    600                1
5   Yogesh  2014    900                2

In [0]:
#@title Find Max and min for a Dataframe column
print("Max is :"+str(empyrsales['Sales'].max()))
print("Max is :"+str(empyrsales['Sales'].min()))

Max is :900
Max is :100


In [0]:
#@title Find Index for Max and min for a Dataframe column
print("Max Index is :"+str(empyrsales['Sales'].idxmax()))
print("Min Index is :"+str(empyrsales['Sales'].idxmin()))

Max Index is :5
Min Index is :1


In [0]:
#@title Get column names
empyrsales.columns

Index(['Name', 'Year', 'Sales', 'NameStartLetter'], dtype='object')

In [0]:
#@title Rename column names
empyrsales.columns=['NewName', 'NewYear', 'Sales', 'NameStartLetter']
empyrsales

NewName NewYear  Sales  NameStartLetter
0    Jassi    2010    450                3
1  Pradeep    2012    100                1
2   Yogesh    2010    300                2
3    Jassi    2010    200                3
4  Pradeep    2016    600                1
5   Yogesh    2014    900                2

In [0]:
#@title Sort column in a dataframe(default ascending)
empyrsales.sort_values('Sales')


NewName NewYear  Sales  NameStartLetter
1  Pradeep    2012    100                1
3    Jassi    2010    200                3
2   Yogesh    2010    300                2
0    Jassi    2010    450                3
4  Pradeep    2016    600                1
5   Yogesh    2014    900                2

In [0]:
#@title Sort column in a dataframe(default descending)
empyrsales.sort_values('Sales',ascending=False)


NewName NewYear  Sales  NameStartLetter
5   Yogesh    2014    900                2
4  Pradeep    2016    600                1
0    Jassi    2010    450                3
2   Yogesh    2010    300                2
3    Jassi    2010    200                3
1  Pradeep    2012    100                1

In [0]:
#@title Concatenating Dataframe
empyrsales

NewName NewYear  Sales  NameStartLetter
0    Jassi    2010    450                3
1  Pradeep    2012    100                1
2   Yogesh    2010    300                2
3    Jassi    2010    200                3
4  Pradeep    2016    600                1
5   Yogesh    2014    900                2

In [0]:
saleid=pd.DataFrame(["9019201","8718199","895669","7747789","22222","333216"],columns=["SalesID"])
saleid

SalesID
0  9019201
1  8718199
2   895669
3  7747789
4    22222
5   333216

In [0]:
pd.concat([empyrsales,saleid],axis=1)

NewName NewYear  Sales  NameStartLetter  SalesID
0    Jassi    2010    450                3  9019201
1  Pradeep    2012    100                1  8718199
2   Yogesh    2010    300                2   895669
3    Jassi    2010    200                3  7747789
4  Pradeep    2016    600                1    22222
5   Yogesh    2014    900                2   333216

In [0]:
#@title Creating Dummy Variables/One hot encoding

pd.get_dummies(empyrsales['NewYear'])

2010  2012  2014  2016
0     1     0     0     0
1     0     1     0     0
2     1     0     0     0
3     1     0     0     0
4     0     0     0     1
5     0     0     1     0

# Input And Output

In [0]:
#@title Check present Working directory and List files within


In [0]:
pwd

'/content'

In [0]:
!ls /content

sample_data


In [0]:
!ls 

sample_data


In [0]:
#@title Mount Google drive


In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
!ls /content

gdrive	sample_data


In [0]:
!ls gdrive/

'My Drive'


In [0]:
!ls "gdrive/My Drive"

'Colab Notebooks'
 DatabricksTutorials.rar
'Data Factory with Data Flow - Course Structure.gsheet'
 expenditures.xlsx
 Interviews
 Jasjyot_Singh_Jaswal_Resume.docx
 Jasjyot_Singh_Jaswal_Resume.pdf
 MyCodeSnippets
'My Password Manager.xlsx'
 MyPPTS
 MyProjects.rar
'Scanned Documents'
 SonyDocs
'Untitled drawing.gdraw'


In [0]:
#@title Read a Sample CSV File without specifying index
csvinput=pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/Tensorflow2.0/Data/SampleInputSalesData")
csvinput

SLNo     Name    Sales
0   255  Jasjyot  4666889
1  4728   Manish  4961789
2  4718  Prateek  3461789

In [0]:
#@title Read a Sample CSV File with specifying index
csvinputindex=pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/Tensorflow2.0/Data/SampleInputSalesData",index_col="SLNo")
csvinputindex

Name    Sales
SLNo                  
255   Jasjyot  4666889
4728   Manish  4961789
4718  Prateek  3461789

In [0]:
#@title Write CSV as Dataframe with index
empyrsales=pd.DataFrame([["Jassi","2010",450],["Pradeep","2012",100],["Yogesh","2010",300],["Jassi","2010",200],["Pradeep","2016",600],["Yogesh","2014",900]],columns=["Name","Year","Sales"])
empyrsales

Name  Year  Sales
0    Jassi  2010    450
1  Pradeep  2012    100
2   Yogesh  2010    300
3    Jassi  2010    200
4  Pradeep  2016    600
5   Yogesh  2014    900

In [0]:
empyrsales.to_csv("/content/gdrive/My Drive/Colab Notebooks/Tensorflow2.0/Data/SampleOutputSalesData.csv",index=True)

In [0]:
#@title Read table content from HTML pages
htmldata=pd.read_html("https://catalog.data.gov/dataset/ncdc-storm-events-database/resource/92666255-e032-4334-a297-daf60b501c95")
htmldata[0]

0                                     1
0                Last updated                     February 27, 2019
1                     Created                     February 27, 2019
2                        Name             Storm Events Database FAQ
3                      Format                          Web Resource
4                     License                  U.S. Government Work
5                     created                         12 months ago
6                          id  92666255-e032-4334-a297-daf60b501c95
7                  package id  dd13b9be-9b00-4639-8ba5-e2035bf4f514
8                    position                                     2
9   resource locator function                           information
10  resource locator protocol                                 HTTPS
11                revision id  5c787f57-bece-4c14-b1e6-e71e877fd7a9
12                      state                                active